language: ruby
rvm:
  - 2.2.3
sudo: false

branches:
  only:
    - master

notifications:
  email: false

before_script: cd website
script: bundle && bundle exec rspec

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
