source 'https://rubygems.org'

gem 'rails', '5.1.5'
gem 'sqlite3'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'

gem 'jquery-rails'
gem 'jbuilder'
gem 'sdoc', group: :doc
gem 'spring', group: :development

gem 'haml-rails'

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'capybara-screenshot'
  gem 'selenium-webdriver'
  gem 'pry'
  gem 'pry-nav'
  gem 'pry-stack_explorer'
  gem 'listen'
end

gem 'bootstrap-sass'
